# Generated by Django 3.1.4 on 2020-12-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(default='Jackie', max_length=30),
        ),
        migrations.AddField(
            model_name='posts',
            name='my_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
